<?php

return [

    // المجموعة الافتراضية عند عدم تحديد $set صراحة
    'default_set' => 'ion', // ion | fa | bi | heroicon | svg

    // الحجم الافتراضي (width/height) المحقون في أيقونات SVG/heroicon التي ماعندهاش
    // حجم محدد في الملف الأصلي — يمنع ظهورها بحجم كبير جدًا بلا CSS إضافي.
    // '1em' يخليها تتبع حجم الخط المحيط بها تلقائيًا (سلوك معياري في مكتبات الأيقونات).
    'svg_size' => '1em',

    // ==========================================================
    // روابط CDN لتضمين مكتبات الأيقونات تلقائيًا عبر:
    //   @statusKitAssets(['fa','bi','ion'])   أو   status_kit_assets(['fa'])
    // هذا يجنبك تثبيت الحزم يدويًا. للتثبيت المحلي/عبر NPM راجع README.md
    // يمكنك تغيير هذه الروابط أو تحديث الإصدارات من هنا بعد نشر الconfig.
    // ==========================================================
    'cdn' => [
        'fa'  => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css',
        'bi'  => 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css',
        'ion' => 'https://unpkg.com/ionicons@7.1.0/dist/ionicons.esm.js', // module script — يُدرج كـ <script type="module">
        'ion_nomodule' => 'https://unpkg.com/ionicons@7.1.0/dist/ionicons.js',
    ],

    // ==========================================================
    // FontAwesome (يتطلب تحميل خط/CSS FontAwesome في المشروع)
    // ==========================================================
    'fa' => [
        'default'  => 'fa-circle',
        'pending'  => 'fa-clock',
        'active'   => 'fa-check-circle',
        'inactive' => 'fa-times-circle',
        'paid'     => 'fa-check-circle',
        'failed'   => 'fa-circle-exclamation',
        'canceled' => 'fa-ban',
        'expired'  => 'fa-hourglass-end',
        'success'  => 'fa-check',
        'warning'  => 'fa-exclamation-triangle',
        'info'     => 'fa-info-circle',
        'refunded' => 'fa-rotate-left',
        'suspended'=> 'fa-ban',
        'banned'   => 'fa-user-slash',
        'rejected' => 'fa-times-circle',
        'approved' => 'fa-check',
        'blocked'  => 'fa-lock',
        'draft'    => 'fa-file',
        'closed'   => 'fa-lock',
        'processing' => 'fa-gear',
        'completed'=> 'fa-check-circle',
        'out_of_stock' => 'fa-box-open',
        'discontinued' => 'fa-ban',
        'email_unverified' => 'fa-envelope',

        'home'     => 'fa-home',
        'user'     => 'fa-user',
        'users'    => 'fa-users',
        'settings' => 'fa-cog',
        'logout'   => 'fa-sign-out-alt',
        'login'    => 'fa-sign-in-alt',
        'register' => 'fa-user-plus',
        'edit'     => 'fa-edit',
        'delete'   => 'fa-trash',
        'wallet'   => 'fa-wallet',
        'money'    => 'fa-money-bill-wave',
        'payment'  => 'fa-credit-card',
        'transaction' => 'fa-exchange-alt',
        'history'  => 'fa-history',
        'search'   => 'fa-search',
        'filter'   => 'fa-filter',
        'download' => 'fa-download',
        'upload'   => 'fa-upload',
        'chart'    => 'fa-chart-line',
        'dashboard'=> 'fa-tachometer-alt',
        'bell'     => 'fa-bell',
        'support'  => 'fa-headset',
        'shield'   => 'fa-shield-alt',
        'store'    => 'fa-store',

        // حالات عامة قابلة لإعادة الاستعمال عبر أي دومين
        'featured'    => 'fa-star',
        'new'         => 'fa-bolt',
        'popular'     => 'fa-fire',
        'verified'    => 'fa-circle-check',
        'recommended' => 'fa-thumbs-up',
        'limited'     => 'fa-hourglass-half',
    ],

    // ==========================================================
    // Bootstrap Icons
    // ==========================================================
    'bi' => [
        'default'  => 'bi-circle',
        'pending'  => 'bi-clock',
        'active'   => 'bi-check-circle',
        'inactive' => 'bi-x-circle',
        'paid'     => 'bi-check-circle',
        'failed'   => 'bi-x-circle',
        'canceled' => 'bi-slash-circle',
        'expired'  => 'bi-hourglass-split',
        'success'  => 'bi-check-lg',
        'warning'  => 'bi-exclamation-triangle',
        'info'     => 'bi-info-circle',
        'refunded' => 'bi-arrow-counterclockwise',
        'suspended'=> 'bi-slash-circle',
        'banned'   => 'bi-person-x',
        'rejected' => 'bi-x-circle',
        'approved' => 'bi-check-lg',
        'blocked'  => 'bi-lock',
        'draft'    => 'bi-file-earmark',
        'closed'   => 'bi-lock',
        'processing' => 'bi-gear',
        'completed'=> 'bi-check-circle',
        'out_of_stock' => 'bi-box-seam',
        'discontinued' => 'bi-slash-circle',
        'email_unverified' => 'bi-envelope',

        'home'     => 'bi-house',
        'user'     => 'bi-person',
        'users'    => 'bi-people',
        'settings' => 'bi-gear',
        'logout'   => 'bi-box-arrow-right',
        'login'    => 'bi-box-arrow-in-right',
        'register' => 'bi-person-plus',
        'edit'     => 'bi-pencil',
        'delete'   => 'bi-trash',
        'wallet'   => 'bi-wallet2',
        'money'    => 'bi-cash',
        'payment'  => 'bi-credit-card',
        'transaction' => 'bi-arrow-left-right',
        'history'  => 'bi-clock-history',
        'search'   => 'bi-search',
        'filter'   => 'bi-funnel',
        'download' => 'bi-download',
        'upload'   => 'bi-upload',
        'chart'    => 'bi-graph-up',
        'dashboard'=> 'bi-speedometer2',
        'bell'     => 'bi-bell',
        'support'  => 'bi-headset',
        'shield'   => 'bi-shield-check',
        'store'    => 'bi-shop',

        // حالات عامة قابلة لإعادة الاستعمال عبر أي دومين
        'featured'    => 'bi-star-fill',
        'new'         => 'bi-lightning-charge-fill',
        'popular'     => 'bi-fire',
        'verified'    => 'bi-patch-check-fill',
        'recommended' => 'bi-hand-thumbs-up-fill',
        'limited'     => 'bi-hourglass-split',
    ],

    // ==========================================================
    // Ionicons
    // ==========================================================
    'ion' => [
        'default'  => 'ellipse-outline',
        'pending'  => 'time-outline',
        'active'   => 'checkmark-circle-outline',
        'inactive' => 'close-circle-outline',
        'paid'     => 'checkmark-done-circle-outline',
        'failed'   => 'alert-circle-outline',
        'canceled' => 'ban-outline',
        'expired'  => 'hourglass-outline',
        'success'  => 'checkmark-outline',
        'warning'  => 'warning-outline',
        'info'     => 'information-circle-outline',
        'refunded' => 'refresh-outline',
        'suspended'=> 'ban-outline',
        'banned'   => 'person-remove-outline',
        'rejected' => 'close-circle-outline',
        'approved' => 'checkmark-outline',
        'blocked'  => 'lock-closed-outline',
        'draft'    => 'document-outline',
        'closed'   => 'lock-closed-outline',
        'processing' => 'settings-outline',
        'completed'=> 'checkmark-done-circle-outline',
        'out_of_stock' => 'cube-outline',
        'discontinued' => 'ban-outline',
        'email_unverified' => 'mail-outline',

        'wallet'   => 'wallet-outline',
        'card'     => 'card-outline',
        'cash'     => 'cash-outline',
        'bank'     => 'business-outline',
        'tag'      => 'pricetag-outline',
        'tags'     => 'pricetags-outline',
        'transaction' => 'swap-horizontal-outline',
        'repeat'   => 'repeat-outline',
        'receipt'  => 'receipt-outline',
        'history'  => 'file-tray-full-outline',
        'trend-up' => 'trending-up-outline',
        'trend-down' => 'trending-down-outline',
        'login'    => 'log-in-outline',
        'logout'   => 'log-out-outline',
        'register' => 'person-add-outline',
        'user'     => 'person-outline',
        'settings' => 'settings-outline',
        'home'     => 'home-outline',
        'dashboard'=> 'grid-outline',
        'edit'     => 'create-outline',
        'save'     => 'save-outline',
        'delete'   => 'trash-outline',
        'add'      => 'add-outline',
        'minus'    => 'remove-circle-outline',
        'eye'      => 'eye-outline',
        'eye-off'  => 'eye-off-outline',
        'reset'    => 'refresh-outline',
        'copy'     => 'copy-outline',
        'chevron-down'  => 'chevron-down-outline',
        'chevron-up'    => 'chevron-up-outline',
        'chevron-left'  => 'chevron-back-outline',
        'chevron-right' => 'chevron-forward-outline',
        'arrow-up'    => 'arrow-up-outline',
        'arrow-down'  => 'arrow-down-outline',
        'arrow-left'  => 'arrow-back-outline',
        'arrow-right' => 'arrow-forward-outline',
        'search'   => 'search-outline',
        'filter'   => 'funnel-outline',
        'download' => 'download-outline',
        'upload'   => 'upload-outline',
        'bell'     => 'notifications-outline',
        'help'     => 'help-circle-outline',
        'shield'   => 'shield-checkmark-outline',
        'qrcode'   => 'qr-code-outline',
        'menu'     => 'menu-outline',
        'apps'     => 'apps-outline',
        'store'    => 'storefront-outline',

        // حالات عامة قابلة لإعادة الاستعمال عبر أي دومين
        'featured'    => 'star',
        'new'         => 'flash-outline',
        'popular'     => 'flame-outline',
        'verified'    => 'shield-checkmark-outline',
        'recommended' => 'thumbs-up-outline',
        'limited'     => 'hourglass-outline',
    ],

    // ==========================================================
    // Heroicons (Outline) — تُعرض كـ SVG من resources/svg/heroicons
    // القيمة هنا = اسم ملف الـ SVG بدون امتداد داخل resources/svg/heroicons/
    // ==========================================================
    'heroicon' => [
        'default'  => 'ellipsis-horizontal-circle',
        'pending'  => 'clock',
        'active'   => 'check-circle',
        'inactive' => 'x-circle',
        'paid'     => 'currency-dollar',
        'failed'   => 'x-circle',
        'canceled' => 'x-mark',
        'expired'  => 'x-circle',
        'success'  => 'check-circle',
        'warning'  => 'exclamation-triangle',
        'info'     => 'information-circle',
        'refunded' => 'arrow-path',
        'suspended'=> 'exclamation-circle',
        'banned'   => 'x-circle',
        'rejected' => 'x-circle',
        'approved' => 'check-circle',
        'blocked'  => 'lock-closed',
        'draft'    => 'lock-open',
        'closed'   => 'lock-closed',
        'processing' => 'cog',
        'completed'=> 'check-circle',
        'out_of_stock' => 'exclamation-triangle',
        'discontinued' => 'x-mark',
        'email_unverified' => 'envelope',

        // خاصة بالأدوار (roles.php سابقًا)
        'shield-exclamation' => 'shield-exclamation',
        'shield-check'       => 'shield-check',
        'chat-bubble'        => 'chat-bubble-left-right',
        'wrench-screwdriver' => 'wrench-screwdriver',
        'building-storefront' => 'building-storefront',
        'user-circle'        => 'user-circle',
        'user'                => 'user',
        'clipboard-check'    => 'clipboard-document-check',

        // حالات عامة قابلة لإعادة الاستعمال عبر أي دومين
        'featured' => 'star',
    ],
];
